---
version: "3"
services:
 devopsdb:
   image: kiran2h/mynew:dbimage
   ports:
     - "3306:3306"

 application:
   image: kiran2h/mynew:appimg
   ports:
     - "1234:8080"
   depends_on:
     - "devopsdb"
